version: '3.8'

services:
  backend:
    container_name: backend-$PROJECT_NAME
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - WORKDIR=$WORK_DIR
        - USERNAME=$USER_NAME
        - HOMEDIR=$HOME_DIR
        - USERID=$USER_ID
        - GROUPID=$GROUP_ID
    ports:
      - $IP:3000:3000
    tty: true
    env_file:
      - ./.env
    volumes:
      - logs:$WORK_DIR/logs
      - ./backend:$WORK_DIR:ro
      - $WORK_DIR/node_modules

volumes:
  logs:
