version: '3.8'

services:
  backend:
    volumes:
      - ./backend:$WORK_DIR:cached
      - vscode-extension-volume:$HOME_DIR/.vscode-server/extensions
      - ./.devcontainer/devcontainer-entrypoint.sh:$HOME_DIR/etc/devcontainer-entrypoint.sh
    user: $USER_ID:$GROUP_ID
    entrypoint:
      - bash
      - $HOME_DIR/etc/devcontainer-entrypoint.sh
    command: sleep infinity

volumes:
  vscode-extension-volume: {}
